// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdwinqxxqzybtanpxlbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkd2lucXh4cXp5YnRhbnB4bGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTI3OTUsImV4cCI6MjA3MDk2ODc5NX0.Am3jex5x6CnzV_k2pqgpSosI47AyE-ncKDyGaooZN_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});